# Colors (Midnight Beach)

[colors.primary]
background = '#0E1B1F'
foreground = '#E6E1CF'

[colors.normal]
black   = '#0B1416'
red     = '#FF7A6E'
green   = '#4ECDC4'
yellow  = '#FFD166'
blue    = '#5FA8D3'
magenta = '#C77DFF'
cyan    = '#72EFDD'
white   = '#DAD7CD'

[colors.bright]
black   = '#3A5A60'
red     = '#FF9F9A'
green   = '#7AE0D1'
yellow  = '#FFE08A'
blue    = '#8ECDFC'
magenta = '#E0AAFF'
cyan    = '#9BF6FF'
white   = '#F4F1DE'

[colors.selection]
text = '#0E1B1F'
background = '#FFD166'
